source 'http://rubygems.org'

gem 'foodcritic'
gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'kitchen-openstack'
gem 'rspec'
gem 'rspec-core'
gem 'chefspec'
gem 'chef'
gem 'rspec-expectations'
gem 'rubocop'
