Encoding:
  Enabled: False
LineLength:
  Max: 600
Documentation:
  Enabled: False
HashSyntax:
  Enabled: False
SpaceBeforeFirstArg:
  Enabled: false
AsciiComments:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 20
