name 'hdp-cloud'
maintainer 'Eric Krenz'
maintainer_email 'eric.krenz@target.com'
license 'All Rights Reserved'
description 'Installs/Configures hdp-cloud'
long_description 'Installs/Configures hdp-cloud'
version '1.0.0'

depends 'selinux'
depends 'autofs'
depends 'nfs'
depends 'yum'
depends 'line'
depends 'entropy'
